spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
    template:
      exchange: spring-exchange
    addresses: amqp://user:pass@localhost:5672,amqp://user:pass@localhost:5673,amqp://user:pass@localhost:5674