version: '3'

services:
  rabbitmq-1:
    image: rabbitmq:3.12.10-management
    container_name: rabbitmq-1
    hostname: rabbitmq-1
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_ERLANG_COOKIE: SUPER1SECRET1COOKIE
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq-1:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  rabbitmq-2:
    image: rabbitmq:3.12.10-management
    container_name: rabbitmq-2
    hostname: rabbitmq-2
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_ERLANG_COOKIE: SUPER1SECRET1COOKIE
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq-2:/var/lib/rabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"

  rabbitmq-3:
    image: rabbitmq:3.12.10-management
    container_name: rabbitmq-3
    hostname: rabbitmq-3
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_ERLANG_COOKIE: SUPER1SECRET1COOKIE
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq-3:/var/lib/rabbitmq
    ports:
      - "15674:15672"
      - "5674:5672"